// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICGmXUGWIWBo3KDD7XxAyYD-H-JPNF2I',
    appId: '1:570300953679:web:06ee5a7a0c0469adb7a63a',
    messagingSenderId: '570300953679',
    projectId: 'crapp-da159',
    authDomain: 'crapp-da159.firebaseapp.com',
    storageBucket: 'crapp-da159.firebasestorage.app',
    measurementId: 'G-J1GX8PJ4F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-llBbORwn0SA5_Z7VQ5St_ZpuRTjy4U',
    appId: '1:570300953679:android:69f7cfa37013c41bb7a63a',
    messagingSenderId: '570300953679',
    projectId: 'crapp-da159',
    storageBucket: 'crapp-da159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4hBjhGWnRygzyuzkT3053RgjffLjEL8',
    appId: '1:570300953679:ios:7b410f594caba67cb7a63a',
    messagingSenderId: '570300953679',
    projectId: 'crapp-da159',
    storageBucket: 'crapp-da159.firebasestorage.app',
    iosBundleId: 'com.example.fixCleanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4hBjhGWnRygzyuzkT3053RgjffLjEL8',
    appId: '1:570300953679:ios:7b410f594caba67cb7a63a',
    messagingSenderId: '570300953679',
    projectId: 'crapp-da159',
    storageBucket: 'crapp-da159.firebasestorage.app',
    iosBundleId: 'com.example.fixCleanProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDICGmXUGWIWBo3KDD7XxAyYD-H-JPNF2I',
    appId: '1:570300953679:web:06ee5a7a0c0469adb7a63a',
    messagingSenderId: '570300953679',
    projectId: 'crapp-da159',
    authDomain: 'crapp-da159.firebaseapp.com',
    storageBucket: 'crapp-da159.firebasestorage.app',
    measurementId: 'G-J1GX8PJ4F8',
  );
}
